---
collections:
  - name: ansible.posix
    version: 1.3.0

  - name: community.general
    version: 3.7.0

  - name: community.zabbix
    version: 1.7.0

  - name: community.postgresql
    version: 2.1.5

  - name: nginxinc.nginx_core
    version: 0.6.0

  - name: community.grafana
    version: 1.4.0

roles:
  - name: geerlingguy.postgresql
    version: 3.2.1

  - name: geerlingguy.php
    version: 4.8.0
