---
- name: Add apt key and grafana repo
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana.list

- name: APT Baseline
  apt:
    update_cache: yes
    upgrade: safe

- name: Install Grafana        
  apt:
    name:
      - grafana

- name: Enable service grafana-server
  ansible.builtin.service:
    name: grafana-server
    enabled: yes

- name: Restart service grafana-server
  ansible.builtin.service:
    name: grafana-server
    state: restarted

- name: Install zabbix grafana plugin
  community.grafana.grafana_plugin:
    name: alexanderzobnin-zabbix-app
    version: 4.2.8
    state: present

- name: Restart service grafana-server
  ansible.builtin.service:
    name: grafana-server
    state: restarted

- name: Pause for 3 minutes to build app cache
  pause:
    minutes: 3
