---
- name: Add apt key and odbc repo
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- apt_repository:
    repo: deb [arch=amd64,armhf,arm64] https://packages.microsoft.com/ubuntu/20.04/prod focal main
    state: present
    filename: mssql-release.list

- name: Install msodbcsql17
  apt:
    name: msodbcsql17
    state: present
    update_cache: yes
  environment:
    ACCEPT_EULA: Y

- name: Install mssql-tools
  apt:
    name: mssql-tools
    state: present
    update_cache: yes
  environment:
    ACCEPT_EULA: Y

- name: Install unixodbc-dev
  apt:
    name: unixodbc-dev
    state: present
    update_cache: yes

- name: Add evn
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: export PATH="$PATH:/opt/mssql-tools/bin"

- name: Source bashrc evn
  ansible.builtin.shell: source ~/.bashrc
  args:
    executable: /bin/bash
