---
zabbix_server_dbhost_run_install: false
zabbix_server_database: pgsql
zabbix_server_database_long: postgresql
zabbix_server_dbport: 5432
zabbix_server_dbhost: 127.0.0.1
zabbix_server_dbname: monitoring
zabbix_server_dbuser: monitoring
zabbix_server_dbpassword: "{{ lookup('file', '../files/psql_pass/monitoring_{{ ansible_host }}_pass.txt') }}"

postgresql_version: 14
postgresql_data_dir: /var/lib/postgresql/14/main
postgresql_bin_path: /usr/lib/postgresql/14/bin/initdb
postgresql_config_path: /etc/postgresql/14/main/
